#!/usr/bin/env bash
# a Bash script that loops from 1 to 10 and:
# - displays bad luck for the 4th loop iteration
# - displays good luck for the 8th loop iteration
# - displays Holberton School for the other iterations
# Using a while loop along with the use of the if , elif ,
# and else statements.

counter=1
while [ $counter -le 10 ]
do
    if [ $counter -eq 4 ]
    then
        echo bad luck
    elif [ $counter -eq 8 ]
    then
        echo good luck
    else
        echo Holberton School
    fi
    ((counter++))
done
