#!/usr/bin/env bash
# a Bash script that gives you information about the holbertonschool file.
# Using if and, else statement

FILE="holbertonschool"
if [ -e "$FILE" ]
    then
    echo "holbertonschool file exists"
    if ! ([ -s "$FILE" ])
        then
        echo "holbertonschool file is empty"
    else
        echo "holbertonschool file is not empty"
    fi
    if [ -f "$FILE" ]
        then
        echo "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi
