#!/usr/bin/env bash
# Bash script that creates an RSA key pair
# Name of the created private key must be holberton
# Number of bits in the created key to be created 4096
# The created key must be protected by the passphrase betty
# google ssh-keygen man
# -f = filename of the keyfile
# -b = number of bits in the key to create
# -N = new passphrase
ssh-keygen -f holberton -b 4096 -N betty
